### ISSUE TITLE
Attempting to save a game file fails

### ISSUE THREAD

**Issue by wyatt8740** [Banbury/zag#1]
I am using Debian Jessie (Debian testing) and OpenJDK 1.7.0.

Attempting to save a game (with the 'save' command) results in the interpreter exiting and this error message:
`org.p2c2e.zag.GlulxException: Could not dispatch call [62] to GLK: java.lang.reflect.InvocationTargetException`
`java.lang.NullPointerException`

**Comment by Banbury** [comment]
Thanks for bringing this to my notice. I will have a look at it first thing in the morning.

**Comment by wyatt8740** [comment]
Thanks. I attached the versions I compiled on the forums, in case for whatever reason it doesn't happen for you with your compiler or something odd like that.

**Comment by Banbury** [comment]
I'm pretty sure, it's a bug on my end. I'm still fighting with streams and haven't even tried saving or loading.

**Comment by wyatt8740** [comment]
Oh, okay. I'd love to help more, but I've not worked with java in 5 years. Thanks for working on this, though. I'll play with it, too - and maybe re-learn some java in the process.
