### ISSUE TITLE
[patch] Scrollbar bouncing and missing every other character with certain look-and-feel settings

### ISSUE THREAD

**Issue by wyatt8740** [Banbury/zag#14]
Zag ignores every other keypress when running with some LAFs due to erroneous assumptions in the window height code. A more detailed description is in the patch. My patch makes it stop ignoring keypresses, but doesn't really fix the scrolling bug.
It does however not bounce up and down anymore, which is enough of an improvement to make me happy.
```
--- a/zag-swing/src/main/java/org/p2c2e/zing/swing/TextBufferWindow.java
+++ b/zag-swing/src/main/java/org/p2c2e/zing/swing/TextBufferWindow.java
@@ -1145,7 +1145,20 @@ public final class TextBufferWindow extends Window implements
 
                if (portRect.height > 5 && viewHeight > portRect.y + portRect.height) {
                        scrollDown(v, viewHeight, portRect.height);
-               } else if (charConsumer != null) {
+               }
+/* we need to scroll down regardless of whether we obtained input and then
+ * accept input that was made - on account of some look-and-feels behaving
+ * strangely (e.g. GTK+, Motif). metal (the swing default usually) and
+ * nimbus were unaffected. The problem was that only every other character
+ * typed was being accepted because of incorrect geometry calculations that
+ * made unsafe assumptions and the buffer was bouncing slightly with each
+ * character entry, scrolled down with the next keystroke, and then up with
+ * the next accepted character again.
+ *
+ * this also makes it follow the convention used in most terminal emulators.
+ */
+//             else if (charConsumer != null) {
+               if (charConsumer != null) {
                        CharInputConsumer cs = charConsumer;
                        charConsumer = null;
 

```

**Comment by Banbury** [comment]
Could you be more specific about the 'wrong assumptions'? And which game did you have the problems with?

**Comment by wyatt8740** [comment]
@Banbury I think it's because the game is arbitrarily adding 5px to the height of the window in a lot of its calculations. I cannot confirm this because my swing knowledge is still lacking.

Happens in every game I try with multiple panels but only when using look and feel settings other than Metal (default) and nimbus from my Debian system.

**Comment by Banbury** [comment]
I haven't done anything in IF for a while, so it would be helpful if you could give me a link to a game, where the problem shows up.

Since this happens only with certain LAFs, it might be a problem calculating the client area of the window.
