### ISSUE TITLE
Add toggle for anti-aliasing.

### ISSUE THREAD

**Issue by Banbury** [Banbury/zag#2]
Some people don't like anti-aliased fonts. Add a toggle to turn it on and off.

**Comment by wyatt8740** [comment]
Thanks for this, too =D I just learned about zag two weeks ago, and it suddenly has activity again! It's amazing!

_edit_ Just downloaded and compiled the source to test - antialiasing is not being turned off with a restart. new bug report has details, apparently it is not correctly parsing configuration files.
