### ISSUE TITLE
'No properties file found. Using default values' when file exists, zag recognizes antialias setting value but does not apply it

### ISSUE THREAD

**Issue by wyatt8740** [Banbury/zag#3]
Same debian system.
when I launch zag and toggle the antialiasing and restart, the tickmark in the 'edit' menu is changed, but the console prints
`No properties file found. Using default values.`
The antialiasing settings (as well as font SIZE, but the font name is preserved) do not carry over.

So this file:
~/.java/.userPrefs/org/p2c2e/zing/style/buffer/normal/prefs.xml
contains:
````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="back-color" value="0"/>
  <entry key="font-italic" value="false"/>
  <entry key="font-size" value="16"/>
  <entry key="font-underline" value="false"/>
  <entry key="font-weight" value="1.0"/>
  <entry key="justification" value="1"/>
  <entry key="left-indent" value="0"/>
  <entry key="paragraph-indent" value="1"/>
  <entry key="right-indent" value="0"/>
  <entry key="text-color" value="13421772"/>
  <entry key="typeface" value="unifont"/>
</map>
````
While typeface is set properly on startup, "font-size" of said typeface is not, remaining at the default value.

and the file
~/.java/.userPrefs/org/p2c2e/zing/style/prefs.xml contains
````
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<map MAP_XML_VERSION="1.0">
  <entry key="use-antialias" value="false"/>
  <entry key="use-hints" value="true"/>
</map>
````
While in the 'edit' menu, one can tell the setting HAS been loaded from the xml file, antialiasing remains unchanged.

**Comment by wyatt8740** [comment]
I have tried clearing my .userPrefs directory and re-running, since those prefs were from an older version, but the newly generated prefs files still retain the same broken functionality.

**Comment by Banbury** [comment]
The 'No property file' message has nothing to do with the preferences. I've added an additional property file (zag.properties) to change the PLAF.
The anti-aliasing setting is stored in the prefs file. I'm not sure why it's not applied. I'll have another look at it, when I'm finished fixing the binary streams.

**Comment by wyatt8740** [comment]
~~I'm beginning to think that the font size may be a problem with unifont or something. It's a bitmapped font (i.e. not a scalable font), and I wonder if that's why it has trouble.~~
Sorry, wasn't thinking. Tried it with a few truetype fonts too. Same problem.

I've only tested the latest version with Linux Mint 16 MATE and Debian Sid (with MATE desktop) so far. I will check it on OS X now.

**Comment by wyatt8740** [comment]
Forgive my lack of java knowledge, but isn't this line just making `use-antialiasing` always be true?

line 530 in zag/zag-swing/src/main/java/org/p2c2e/zing/swing/Glk.java:
````
Style.use_antialiasing = stylep.getBoolean("use-antialiasing", true);
````

**Comment by Banbury** [comment]
It's a typo. It should read 
Style.use_antialiasing = stylep.getBoolean("use-antialias", true);

I have fixed it, but haven't pushed it yet.

**Comment by wyatt8740** [comment]
Wow, so I pinpointed the exact line without realizing quite what it did! This must be my day.
