### ISSUE TITLE
Zag allows writing to ROM.

### ISSUE THREAD

**Issue by Banbury** [Banbury/zag#6]
If a game tries writing to ROM, the interpreter should fail with an error message.

Usually this shouldn't happen, but there are some old Superglús games, which write to the ROM, owing to a bug in the compiler.

For compatibility reasons there should be a property value to turn the new behaviour off.

**Comment by wyatt8740** [comment]
Write to the ROM, meaning the game file itself? or read-only memory on your computer, like a ROM chip? I don't have any knowledge to contribute here, but I'm interested.

**Comment by Banbury** [comment]
A Glulx game can define it's own ROM in the interpreters memory, where constants and the like are stored. I think the Glulx compiler is responsible for defining this value. The interpreter is supposed to not write into this area. On the other hand the compiler shouldn't create games, which write to ROM, in the first place.
This has nothing to do with the physical ROM.

**Comment by wyatt8740** [comment]
I didn't think so - just was a little confused, since I know little about the glulx and Z virtual machines. Thanks for clearing it up.
